message(STATUS "Using custom FindBoost.cmake")
set(Boost_FOUND TRUE)
set(Boost_INCLUDE_DIR "${CMAKE_SOURCE_DIR}/externals/boost/includes")
set(Boost_LIBRARIES boost_1_67_0)

if (TARGET Boost::program_options)
else()
    add_library(Boost::program_options STATIC IMPORTED)
    add_library(Boost::fiber STATIC IMPORTED)
    add_library(Boost::context STATIC IMPORTED)
    add_library(Boost::thread STATIC IMPORTED)
    add_library(Boost::log STATIC IMPORTED)
    add_library(Boost::filesystem STATIC IMPORTED)
    add_library(Boost::system STATIC IMPORTED)
    add_library(Boost::boost STATIC IMPORTED)
    set_property(TARGET Boost::boost PROPERTY INTERFACE_INCLUDE_DIRECTORIES ${Boost_INCLUDE_DIR})
endif()
