#include "eosio.system/src/eosio.system.cpp"
#include "eosio.system/src/delegate_bandwidth.cpp"
#include "eosio.system/src/exchange_state.cpp"
#include "eosio.system/src/native.cpp"
#include "eosio.system/src/producer_pay.cpp"
#include "eosio.system/src/rex.cpp"
#include "eosio.system/src/voting.cpp"
#include "eosio.system/src/activate_accounts.cpp"

#include "eosio.token/src/eosio.token.cpp"
#include "main_eosio_token.cpp"
#include "main_eosio_contract.cpp"
